global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "wsrestinmuebles"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "468776618910.dkr.ecr.us-east-1.amazonaws.com/wsrestinmuebles"
    tag: 1.0.0.1
    pullPolicy: IfNotPresent

  # Namespace where release will be deployed
  namespace: wsrestinmuebles-desa
  clusterName: desa
  
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: ""
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: ""

java:

  api:
    resources: 
      requests:
        cpu: 500m
        memory: 1100Mi
      limits:
        cpu: 1000m
        memory: 1100Mi

    # commandArgs custom command argument on deployment pod template
    # commandArgs: "java -jar server.jar"

    terminationGracePeriodSeconds: 60
    revisionHistoryLimit: 2
    replicacount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70

    securityContext:
      enabled: true
      # runAsUser: 1000
      # runAsGroup: 1000
      runAsUser: 0
      runAsGroup: 0      
      scc:
        enabled : true
        rootUser: true

    env: 
      - name: RUNTIME_ENVIRONMENT
        value: ENVUPPERCASE
      - name: PROXY_URL
        value: http://proxyurllowercase.gobiernocba.gov.ar/
      - name: PROXY_PORT
        value: '8080'
      - name: NON_PROXY_HOSTS
        value: "localhost|127.0.0.1|*.test.cba.gov.ar|*.rentasweb.gob.ar|*.cba.gov.ar|*.cba.gob.ar|*.rentascordoba.gob.ar|10.42.*|10.250.*|lb-internal"
      - name: PERM_SIZE
        value: 256m
      - name: MAX_PERM_SIZE
        value: 256m
      - name: XMS
        value: 1024m
      - name: XMX
        value: 1024m

    envVars:
      secretVars:
        - name: ptax-db 
        - name: dbcredentials-appnamelowercase-envlowercase
      configMapVars: {}

    livenessProbe:
      enabled: true
      path: /
      port: 8080
      failureThreshold: 3
      initialDelaySeconds: 120
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      enabled: true
      path: /
      port: 8080
      failureThreshold: 3
      initialDelaySeconds: 120
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    volumeMounts: 
      - mountPath: /tmp/cacerts/DGCIT_Root_CA.crt
        name: dgcit-root-ca
        subPath: DGCIT_Root_CA.crt
      - mountPath: /opt/zipass
        name: zipass
        subPath: zipass 
      - mountPath: /run.sh
        name: run-script
        subPath: run.sh   
    extraVolumes:
      - name: dgcit-root-ca
        type: secret
        secretName: dgcit-root-ca
      - name: zipass
        type: secret
        secretName: zipass
      - name: run-script
        type: configMap
        defaultMode: 0770

    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: hostlowercase
          paths:
            - path: /PREFIJO/
              pathType: Prefix
