apiVersion: v2
name: wsrestgalileo-eks
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy WSRestGalileo proyect based on java Helm chart.
keywords:
  - javaeks
dependencies:
- name: javaeks
  version: 0.0.1
  # repository: "http://--/"
  repository: "file://../javaeks"
