project:
  repository_url: https://git.rentasweb.gob.ar/copernico/ws-cop-manager-recuperador-de-ants.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: ws-manager-recuperador-ants-cop
