global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "api-reprocesa-cuit-cop"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "registro.kolektor.com.ar:5000/api-reprocesa-cuit-cop"
    tag: release-0.0.1
    pullPolicy: Always

  # Namespace where release will be deployed
  namespace: api-reprocesa-cuit-cop-prod
  clusterName: prod-api-reprocesa-cuit-cop

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "ClusterFirst"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config

node:
  api:
    resources: 
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    # commandArgs custom command argument on deployment pod template
    # commandArgs: "java -jar server.jar"
    
    nodeSelector: |
      node-role.kubernetes.io/cop: ""

    terminationGracePeriodSeconds: 30
    revisionHistoryLimit: 2
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
      
    tolerations: |
      - key: "node-role.kubernetes.io/worker"
        operator: "Exists"
        value: ""

    securityContext:
      enabled: false
      runAsUser: 1000
      runAsGroup: 1000
      scc:
        enabled : false
        rootUser: false
    envVars:
      secretVars:
        - name: api-reprocesa-cuit-secret
      configMapVars: {}

    livenessProbe:
      enabled: false
      path: /
      port: 3000
      failureThreshold: 3
      initialDelaySeconds: 20
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      enabled: false
      path: /
      port: 3000
      failureThreshold: 3
      initialDelaySeconds: 20
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    volumeMounts: {}
    extraVolumes: {}
    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: "api-reprocesa-cuit-cop.apps.apps.prod-rentas.gobiernocba.gov.ar"
          paths:
            - path: /
              pathType: Prefix
    service:
      port: 3000
      targetPort: 3000

