project:
  repository_url: https://git.rentasweb.gob.ar/copernico/ws-rules-manager-session-cleaner.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: ws-rules-manager-session-cleaner-cop
