apiVersion: v2
name: wsrestcaptcha
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy wsrestcaptcha proyect based on node Helm chart.
keywords:
  - node
dependencies:
- name: node
  version: 0.0.1
  # repository: "http://--/"
  repository: "file://../node"
