global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: wsrestcaptcha
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: registry-sip.cba.gov.ar:5000/wsrestcaptcha
    tag: release-0.0.48
    pullPolicy: IfNotPresent

  # Namespace where release will be deployed
  namespace: wsrestcaptcha-test
  clusterName: test-rentas

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "None"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: 'nameservers: ["10.250.1.50", "10.250.1.51"]'

node:

  api:
    resources: 
      limits:
        cpu: 1000m
        memory: 1100Mi

    # commandArgs custom command argument on deployment pod template
    # commandArgs: "java -jar server.jar"

    terminationGracePeriodSeconds: 1
    revisionHistoryLimit: 2
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70

    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 1000      
      scc:
        enabled : true
        rootUser: false

    env: 
      - name: RUNTIME_ENVIRONMENT
        value: TEST
      - name: PROXY_URL
        value: proxysrv.gobiernocba.gov.ar
      - name: PROXY_PORT
        value: '8080'
      - name: NON_PROXY_HOSTS
        value: "localhost|127.0.0.1|*.test.cba.gov.ar|*.rentasweb.gob.ar|*.cba.gov.ar|*.cba.gob.ar|*.gobiernocba.gov.ar|*.rentascordoba.gob.ar|10.42.*|10.250.*|lb-internal"
      - name: PORT
        value: 3000
      - name: TZ
        value: America/Argentina/Buenos_Aires

    envVars:
      secretVars:
        - name: ptax-db
        - name: dbcredentials-wsrestcaptcha-test
        - name: captchacredentials-wsrestcaptcha-test
      configMapVars: {}

    livenessProbe:
      enabled: true
      path: /wsrest-captcha/healthz
      port: 3000
      failureThreshold: 3
      initialDelaySeconds: 80
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      enabled: true
      path: /wsrest-captcha/healthz
      port: 3000
      failureThreshold: 3
      initialDelaySeconds: 80
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    volumeMounts: 
      - mountPath: /tmp/cacerts/DGCIT_Root_CA.crt
        name: dgcit-root-ca
        subPath: DGCIT_Root_CA.crt 
    extraVolumes:
      - name: dgcit-root-ca
        type: secret
        secretName: dgcit-root-ca

    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: apps.apps.test-rentas-os.gobiernocba.gov.ar
          paths:
            - path: /wsrest-captcha/
              pathType: Prefix
    service:
        port: 80
        targetPort: 3000
