global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "front-demo-cop"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "registry-sip.cba.gov.ar:5000/demo-fe-cop"
    tag: release-0.0.47
    pullPolicy: Always

  # Namespace where release will be deployed
  namespace: demo-fe-cop-preprod
  clusterName: preprod-demo-fe-cop

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "ClusterFirst"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: 'nameservers: ["10.250.1.50", "10.250.1.51"]'
node:
  api:
    resources: 
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    # commandArgs custom command argument on deployment pod template
    # commandArgs: "nodejs -jar server.jar"
    terminationGracePeriodSeconds: 30
    revisionHistoryLimit: 2
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70

    securityContext:
      enabled: false
      runAsUser: 1000
      runAsGroup: 1000
      scc:
        enabled : false
        rootUser: false
    envVars:
      secretVars:
        - name: demofe-secret
      configMapVars: {}

    livenessProbe:
      enabled: false
      path: /
      port: 
      failureThreshold: 30
      initialDelaySeconds: 30
      successThreshold: 1
      periodSeconds: 10
      timeoutSeconds: 1

    readinessProbe:
      enabled: false
      path: /
      port: 3000
      failureThreshold: 3
      initialDelaySeconds: 20
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    volumeMounts: 
      - mountPath: /var/www/env-config.js
        name: env-config
        subPath: env-config.js

    extraVolumes:
      - name: env-config
        type: secret
        secretName: demofe-secret
        items:
          - key: env-config.js
            path: env-config.js


    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: "demo-fe-cop.apps.apps.preprod-rentas-os.gobiernocba.gov.ar"
          paths:
            - path: /
              pathType: Prefix
    service:
      port: 80
      targetPort: 80

