global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "wsrestdeudasujeto-cop-feature"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "registro.kolektor.com.ar:5000/wsrestdeudasujeto-cop"
    tag: release-0.0.15
    pullPolicy: Always

  # Namespace where release will be deployed
  namespace: wsrestdeudasujeto-cop-preprod-feature
  clusterName: preprod-wsrestdeudasujeto-cop

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "ClusterFirst"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: 'nameservers: ["10.250.1.50", "10.250.1.51"]'
node:
  api:
    resources: 
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    # commandArgs custom command argument on deployment pod template
    terminationGracePeriodSeconds: 30
    revisionHistoryLimit: 2
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70

    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 1000
      scc:
        enabled : true
        rootUser: false
    envVars:
      secretVars:
        - name: wsrestdeudasujeto-cop-secret
      configMapVars: {}

    livenessProbe:
      enabled: false
      path: /
      port: 3000
      failureThreshold: 30
      initialDelaySeconds: 30
      successThreshold: 1
      periodSeconds: 10
      timeoutSeconds: 1

    readinessProbe:
      enabled: false
      path: /
      port: 3000
      failureThreshold: 3
      initialDelaySeconds: 20
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: "cop-wsrestdeudasujeto-feature.apps.apps.preprod-rentas-os.gobiernocba.gov.ar"
          paths:
            - path: /
              pathType: Prefix
    service:
      port: 3000
      targetPort: 3000