project:
  repository_url: https://git.rentasweb.gob.ar/copernico/ws-cop-manager-read-obligaciones.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: ws-cop-manager-read-obligaciones-cop
