apiVersion: v2
name: excepciones-cop
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy excepciones-cop proyect based on NodeJS Helm chart.
keywords:
  - node
dependencies:
- name: node
  version: 0.0.1
  repository: "file://../node"