project:
  repository_url: https://git.rentasweb.gob.ar/Architecture/keycloak/keycloak-spi-representados-mapper.git
  ecr_registry: 634937925704.dkr.ecr.us-west-2.amazonaws.com
  ecr_repository: keycloak-eks