project:
  repository_url: https://git.rentasweb.gob.ar/copernico/pcs-peperina.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: pcs-cop
  sbt_cmd: pcs/docker:stage
  dockerfile_path: ./pcs/Dockerfile