global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "magicbox"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "registry-sip.cba.gov.ar:5000/magicbox"
    tag: release-1.25.7
    pullPolicy: IfNotPresent

  # Namespace where release will be deployed
  namespace: magicbox-desa
  clusterName: desa-magicbox

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "None"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: 'nameservers: ["10.250.1.50", "10.250.1.51"]'

python:

  api:
    resources: 
      limits:
        cpu: 500m
        memory: 512Mi

    # commandArgs custom command argument on deployment pod template
    # commandArgs: "vunicorn server start:dev"

    terminationGracePeriodSeconds: 1
    revisionHistoryLimit: 2
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70

    securityContext:
      enabled: false

    env: 
      - name: PROXY_URL
        value: proxysrv.gobiernocba.gov.ar
      - name: PROXY_PORT
        value: '8080'
      - name: NON_PROXY_HOSTS
        value: "localhost|127.0.0.1|*.desa.cba.gov.ar|*.rentasweb.gob.ar|*.cba.gov.ar|*.cba.gob.ar|*.gobiernocba.gov.ar|*.rentascordoba.gob.ar|10.42.*|10.250.*|lb-internal"

    envVars:
      secretVars:
        - name: magicbox-secret
        - name: more-db
      configMapVars: {}

    livenessProbe:
      enabled: false
      path: "/health"
      port: 5000
      failureThreshold: 30
      initialDelaySeconds: 30
      successThreshold: 1
      periodSeconds: 10
      timeoutSeconds: 1

    readinessProbe:
      enabled: false

    volumeMounts: {}
    extraVolumes: {}

    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts: 
        - host: "internal-apps.apps.desa-rentas.gobiernocba.gov.ar"
          paths:
            - path: /magicbox
              pathType: Prefix

    service:
        port: 5000
        targetPort: 5000
