apiVersion: v2
name: backproductividadfip
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy backproductividadfip proyect based on NodeJS Helm chart.
keywords:
  - node
dependencies:
- name: node
  version: 0.0.1
  # repository: "http://--/"
  repository: "file://../node"
