piVersion: v2
name: clean-up-tool
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy pcs-cop proyect based on scala Helm chart.
keywords:
  - scala
dependencies:
- name: scala
  version: 0.0.1
  # repository: "http://--/"
  repository: "file://../scala"
