global:
  enabled: true
  projectName: ia-dof
  image:
    repository: 634937925704.dkr.ecr.us-west-2.amazonaws.com/ia-dof
    tag: release-0.0.52
    pullPolicy: IfNotPresent
  namespace: ia-dof-prod
  clusterName: eks-prod-rentas
  dnsPolicy: "ClusterFirst"
ingress: {}
pythoneks:
  api:
    enabled: true
    resources:

      limits:
        cpu: 1500m
        memory: 3000Mi
    terminationGracePeriodSeconds: 1
    revisionHistoryLimit: 2
    replicas: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    env:
      - name: RUNTIME_ENVIRONMENT
        value: PROD
      - name: PROXY_URL
        value: proxysrv.gobiernocba.gov.ar
      - name: PROXY_PORT
        value: '8080'
      - name: NON_PROXY_HOSTS
        value: "localhost|127.0.0.1|*.test.cba.gov.ar|*.rentasweb.gob.ar|*.cba.gov.ar|*.cba.gob.ar|*.gobiernocba.gov.ar|*.rentascordoba.gob.ar|10.42.*|10.250.*|lb-internal"
      - name: PORT
        value: "3000"
      - name: TZ
        value: America/Argentina/Buenos_Aires
      - name: DB_DRIVER
        value: postgresql+asyncpg
      - name: VDB_DRIVER
        value: postgresql+psycopg2
      - name: DB_PORT
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: DB_PORT
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: DB_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: DB_PASSWORD
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: DB_HOST
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: DB_NAME
      - name: VDB_NAME
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: VDB_NAME
      - name: OLLAMA_LLM_MODEL_NAME
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: OLLAMA_LLM_MODEL_NAME
      - name: OLLAMA_EMBEDDING_MODEL_NAME
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: OLLAMA_EMBEDDING_MODEL_NAME
      - name: OLLAMA_URL
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: OLLAMA_URL
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: AWS_SECRET_ACCESS_KEY
      - name: EMBEDDING_PROVIDER
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: EMBEDDING_PROVIDER
      - name: LLM_PROVIDER
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: LLM_PROVIDER
      - name: BEDROCK_MODEL_ID
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: BEDROCK_MODEL_ID
      - name: BEDROCK_REGION
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: BEDROCK_REGION
      - name: S3_WORKER_ENABLED
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: S3_WORKER_ENABLED
      - name: S3_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: S3_BUCKET_NAME
      - name: S3_KEY_PREFIX
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: S3_KEY_PREFIX
      - name: S3_WORKER_POLL_INTERVAL
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: S3_WORKER_POLL_INTERVAL
      - name: LOGGER_LEVEL
        valueFrom:
          secretKeyRef:
            name: ia-dof-secret
            key: LOGGER_LEVEL
    livenessProbe:
      enabled: true
      path: /ia-dof/healthz
      port: 5000
      scheme: HTTP
      failureThreshold: 3
      initialDelaySeconds: 30
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10
    readinessProbe:
      enabled: true
      path: /ia-dof/healthz
      port: 5000
      scheme: HTTP
      failureThreshold: 3
      initialDelaySeconds: 30
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10
  # Config Volumen
  volumeMounts: {}
  extraVolumes: {}
  ingress:
    enabled: true
    className: "alb"
    name: "ingress-sip-prod"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: "alb"
      alb.ingress.kubernetes.io/load-balancer-name: alb-eks-prod
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:634937925704:certificate/b1554377-14a0-45b1-b6d4-59822faf5e5c
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/group.name: alb-eks-prod
      alb.ingress.kubernetes.io/group.order: "1"
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=100
      alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:us-west-2:634937925704:regional/webacl/Web_ACL_ALB_EKS/26ca6840-3acd-4ecc-939e-14767ee1bc5f
      alb.ingress.kubernetes.io/enable-cors: "true"
      alb.ingress.kubernetes.io/cors-allow-origin: "https://rentascordoba.gob.ar"
      alb.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, DELETE, POST, OPTIONS"
      alb.ingress.kubernetes.io/cors-allow-headers: "Content-Type,X-Authorization,authorization,captcha,cuit,timestamp,X-Requested-With,url,evento,responsetype,cuitiniciador,cuittitular,usuariofront,sectorfront"
      alb.ingress.kubernetes.io/cors-allow-credentials: "true"
    hosts:
      - host: backend-cloud-internal.inteligenciafiscal.gob.ar
        paths:
          - path: /ia-dof
            pathType: Prefix
            backend:
              service: 
                name: ia-dof
                port:
                  number: 80
      - host: backend-cloud.inteligenciafiscal.gob.ar
        paths:
          - path: /ia-dof
            pathType: Prefix
            backend:
              service: 
                name: ia-dof
                port:
                  number: 80

  service:
    enabled: true
    name: ia-dof
    type: ClusterIP
    port: 80
    targetPort: 5000
    labels:
      environment: prod
