apiVersion: v2
name: wsrestdatosdistribuciondc
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy wsrestdatosdistribuciondc proyect based on java Helm chart.
keywords:
  - java
dependencies:
- name: java
  version: 0.0.1
  # repository: "http://--/" #TEST commits
  repository: "file://../java"
