project:
  repository_url: https://git.rentasweb.gob.ar/impuestos/ws-imp-manager-generacion-obligaciones-inmobiliario.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: ws-manager-gen-obligaciones-inmobiliario-cop
