global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "readside-cop"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "registry-sip.cba.gov.ar:5000/readside-cop"
    tag: release-readside-1.1.11
    pullPolicy: IfNotPresent

  # Namespace where release will be deployed
  namespace: readside-cop-preprod
  clusterName: preprod-readside-cop

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "ClusterFirst"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
#  dnsConfig: 'nameservers: ["10.250.1.50", "10.250.1.51"]'

scala:
  api:
    resources: 
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: "3"
        memory: 3144Mi

    # commandArgs custom command argument on deployment pod template
    # commandArgs: "java -jar server.jar"

    terminationGracePeriodSeconds: 30
    revisionHistoryLimit: 2
    replicaCount: 3
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    
    rbac:
      clusterRole: true
      reader: false
      serviceAccount: true

    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 1000      
      scc:
        enabled : true
        rootUser: true
    extraLabels:
      app: readside-cluster 

    ports:
      - containerPort: 9091
        name: monitoring       
      - containerPort: 9095
        name: monitor        
      - containerPort: 2554
        name: remoting        
      - containerPort: 8082
        name: api        
      - containerPort: 8559
        name: management          
    env:
      - name: POD_NAMESPACE
        podInfo: metadata.namespace
      - name: CLUSTER_IP
        podInfo: status.podIP
      - name: JAVA_OPTS
        value: -Xmx2G -Xms1G -XX:MaxRAMPercentage=85 -XX:MaxGCPauseMillis=500
      - name: MAX_CONCURRENT_REQUESTS
        value: "512"
      - name: MAX_REQUESTS_PER_CONNECTION
        value: "1024"
      - name: POOL_LOCAL_SIZE
        value: "2"
      - name: POOL_REMOTE_SIZE
        value: "1" 
    envVars:
      secretVars:
        - name: readside-cassandra-secret
        - name: readside-config-secret

      configMapVars: {}

    livenessProbe:
      enabled: true
      path: /alive
      port: 8559
      failureThreshold: 10
      initialDelaySeconds: 20
      successThreshold: 1
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      enabled: true
      path: /ready
      port: 8559
      failureThreshold: 10
      initialDelaySeconds: 20
      successThreshold: 1
      periodSeconds: 10
      timeoutSeconds: 10

    lifecycle:
      postStart:
        command: curl --retry 10000 -f --retry-all-errors --retry-delay 5  -X POST http://localhost:8082/kafka/start &
      preStop:
        command: ' while curl -X POST http://localhost:8082/api/system/shutdown; do sleep 10; done'

    volumeMounts: {}
    extraVolumes: {}

    ## Allowing use of ingress controllers
    ingress:
      enabled: false
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: gobiernocba.gov.ar
          paths:
            - path: /
              pathType: Prefix
    service:
      enabled: true
      serviceName:
        - enabled: true
          name: readside-monitor
          type: ClusterIP
          ports:
            - port: 9091
              portName: monitoring
              targetPort: 9091
            - port: 9095
              portName: monitor
              targetPort: 9095   
        - enabled: true
          name: readside-cluster
          type: NodePort
          ports:
            - port: 8082        
              portName: api
              targetPort: 8082
        - enabled: true
          name: readside-api
          type: ClusterIP
          ports:
            - port: 8082        
              portName: api
              targetPort: 8082
        - enabled: true
          name: application-dns-internal
          labels:
            enabled: false
          clusterIP: None
          publishNotReadyAddresses: true
          selector:
            app: pcs 
          ports:
            - port: 8559
              portName: management
              targetPort: 8559
            - port: 2554
              portName: remoting
              targetPort: 2554 
######### service monitor ######                    
    serviceMonitor:
      enabled:  true
      selector:
        - port: monitoring
          interval: 10s
          honorLabels: true
          path: /metrics
        - port: monitor
          interval: 10s
          honorLabels: true
          path: /metrics
