{{- if .Values.filebeat.openshiftRbac }}
{{- $fullName := .Values.filebeat.fullnameOverride -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName | quote }}
  annotations:
    {{- with .Values.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ $fullName | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
{{- end -}}