apiVersion: v2
name: wsrestcomposicionmail
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy WSRestComposicionMail proyect based on java Helm chart.
keywords:
  - java
dependencies:
- name: java
  version: 0.0.1
  # repository: "http://--/"
  repository: "file://../java"
