global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "apicodeadmin"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "registry-sip.cba.gov.ar:5000/api-codeadmin"
    tag: release-0.0.21
    pullPolicy: IfNotPresent

  # Namespace where release will be deployed
  namespace: apicodeadmin-desa
  clusterName: desa-apicodeadmin

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "None"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: 'nameservers: ["10.250.1.50", "10.250.1.51"]'

python:

  api:
    resources: 
      limits:
        cpu: 500m
        memory: 1100Mi
      requests:
        cpu: 250m
        memory: 512Mi      

    # commandArgs custom command argument on deployment pod template
    # commandArgs: "vunicorn server start:dev"

    terminationGracePeriodSeconds: 1
    revisionHistoryLimit: 2
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70

    securityContext:
      enabled: false

    env: 
      - name: PROXY_URL
        value: proxysrv.gobiernocba.gov.ar
      - name: PROXY_PORT
        value: '8080'
      - name: NON_PROXY_HOSTS
        value: "localhost|127.0.0.1|*.desa.cba.gov.ar|*.rentasweb.gob.ar|*.cba.gov.ar|*.cba.gob.ar|*.gobiernocba.gov.ar|*.rentascordoba.gob.ar|10.42.*|10.250.*|lb-internal"
      - name: PERM_SIZE
        value: 256m
      - name: MAX_PERM_SIZE
        value: 256m
      - name: XMS
        value: 1024m
      - name: XMX
        value: 1024m
      - name: PORT
        value: 3001

    envVars:
      secretVars:
        - name: ptax-db
        - name: envsettings-apicodeadmin-desa
        - name: envs-azure-apicodeadmin-desa
      configMapVars: {}

    livenessProbe:
      enabled: true
      path: /quickdev-api/healthz
      port: 3001
      failureThreshold: 3
      initialDelaySeconds: 150
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      enabled: true
      path: /quickdev-api/healthz
      port: 3001
      failureThreshold: 3
      initialDelaySeconds: 150
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    volumeMounts: 
      - mountPath: /tmp/cacerts/DGCIT_Root_CA.crt
        name: dgcit-root-ca
        subPath: DGCIT_Root_CA.crt 
    extraVolumes:
      - name: dgcit-root-ca
        type: secret
        secretName: dgcit-root-ca

    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: apps.apps.desa-rentas.gobiernocba.gov.ar
          paths:
            - path: /quickdev-api/
              pathType: Prefix

    service:
        port: 80
        targetPort: 3001
