apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.projectName }}-sa
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.global.projectName }}-discovery-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
      - update

  - apiGroups: [""]
    resources:
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.projectName }}-discovery-binding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.projectName }}-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.global.projectName }}-discovery-role
  apiGroup: rbac.authorization.k8s.io
