project:
  repository_url: https://git.rentasweb.gob.ar/copernico/ws-cop-manager-read-grandes-emisores-cantidad-objetos.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: ws-manager-ge-cantidad-objetos-cop
