project:
  repository_url: https://git.rentasweb.gob.ar/registro_propiedad/microservicios_notificaciones.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: microservicionotificaciones-rgp
