project:
  repository_url: https://git.rentasweb.gob.ar/InteligenciaFiscal/automations/determinacion-de-oficio/be-dof.git
  ecr_registry: 634937925704.dkr.ecr.us-west-2.amazonaws.com
  ecr_repository: be-dof
