global:
  clusterName: "prod"

auth:
  deploy_web:
    applications:
      - rentas
      - sellosrentas
      - wsrestant
      - wsrestauditoria
      - wsrestautomotores
      - wsrestcalculador
      - wsrestcomposicionmail
      - wsrestdeudaant
      - wsrestdeudafront
      - wsrestdeudar2
      - wsrestembarcaciones
      - wsrestimpuestos
      - wsrestinformacionusuariorentas
      - wsrestingresosbrutos
      - wsrestinmuebles
      - wsrestpagos
      - wsrestpsrm
      - wsrestresoluciones
      - wsrestsujetos
      - wsresttipas
      - wsresttramites
      - wsresttributario
      - wsrestvalidadorexterno
      - wsrestkepler
      - kontaktar
      - wsrestpagos360
      - wsrestcontribuyentesespeciales
      - wsrestabmtramites
      - wsrestgatewaylogin
      - wsrestregimenretper
      - wsrestsellos
      - wsrestsellosimportararchivo
      - wsrestsellosprocesararchivo
      - turnero
      - wsrestobjetos-cop
      - fe-inicio
      - fe-kosmos-kit
      - wsselloescribano
     

  deploy_dao:
    applications:
      - wsrestcuotaunica
      - wsrestdaopsrm
      - wsrestdebitoautomatico
      - wsrestdebitos
      - wsrestmercadopagodebitos
      - wsrestpayperticdebitos
      - wsrestadhesiondao
      - wsrestcantidaddebitos360
  
  deploy_dc:
    applications:
      - cronjobpsrm
      - rentas
      - cronjobunificado
      - wsrestdc

#  deploy_gant:
#    applications:

  deploy_pagos:
    applications:
      - wsrestdecidir
      - wsrestlink
      - wsrestmediospago
      - wsrestmobbexgateway
      - wsrestmercadopagogateway
      - wsrestpsrmgateway
      - wsrestreportesant  
      - wsrestseguridaddatos
      - wsrestbilleteragateway
      - wsrestpagoelectronico
      - wsrestpagos360
      - wsrestpaypertic
      - wsresttransaccionespagos
      - wsrestcomprobantes
      - wsresthistorial360

  deploy_planes_de_pagos:
    applications:
      - wsrestplanespagos
      - wsrestgalileo
      - wsrestgalileo-feature
      - wsrestids
      - wsrestidm

  deploy_impuestos:
    applications:
      - wsdeudapatente
      - wsrestfta
      - wscronfta

  deploy_sellos:
    applications:
      - wsrestsellos
      - wsrestsellosimportararchivo
      - wsrestsellosprocesararchivo

  deploy_dif:
    applications:
    - backendinteligenciafiscal
    
  deploy_copernico:
    applications:
    - readside-cop
    - pcs-cop
    - wsrestobjetos-cop
    - wsrest-sujeto-v8-cop
    - ws-cop-manager-read-objetos-cop
    - ws-cop-manager-read-obligaciones-cop
    - ws-cop-manager-read-objetos-obligaciones-cop
    - ws-redis-manager-read-rule-cop
    - ws-redis-manager-read-rules-cop
    - ws-redis-manager-upsert-data-cop
    - ws-redis-manager-read-keys-cop
    - ws-rules-manager-backup-cop
    - ws-rules-manager-permissions-cop
    - ws-rules-manager-read-admin-cop
    - ws-rules-manager-read-admins-cop

  deploy_fta:
    applications:
    - backftagoasig

  deploy_puntajefip: 
    applications:
    - 
  
  deploy_crm:
    applications:
    - wsrestgestiones360
    - wsrestdfe360
    - wsrestaud360
