global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "drools-wb"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "registry-sip.cba.gov.ar:5000/testdrools"
    tag: 7.17.0.Final
    pullPolicy: IfNotPresent

  # Namespace where release will be deployed
  namespace: drools-wb-desa
  clusterName: desa-rentas

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: "None"
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: 'nameservers: ["10.250.1.50", "10.250.1.51"]'

java:

  api:
    resources: 
      limits:
        cpu: 1000m
        memory: 2200Mi

    # commandArgs custom command argument on deployment pod template
    # commandArgs: "java -jar server.jar"

    terminationGracePeriodSeconds: 1
    revisionHistoryLimit: 2
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70

    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 1000      
      scc:
        enabled : true
        rootUser: false

    env: 
      - name: RUNTIME_ENVIRONMENT
        value: DESA

    envVars:
      secretVars:
        - name: drools-secret
    #envVars:
    #  secretVars:
    #    - name: ptax-db
    #    - name: dbcredentials-cronjobpsrm-desa
    #  configMapVars: {}

    livenessProbe:
      enabled: false
      path: 
      port: 8080
      failureThreshold: 3
      initialDelaySeconds: 80
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      enabled: false
      path: 
      port: 8080
      failureThreshold: 3
      initialDelaySeconds: 80
      successThreshold: 1
      periodSeconds: 30
      timeoutSeconds: 10

    volumeMounts: 
      - mountPath: /tmp/cacerts/DGCIT_Root_CA.crt
        name: dgcit-root-ca
        subPath: DGCIT_Root_CA.crt 
    extraVolumes:
      - name: dgcit-root-ca
        type: secret
        secretName: dgcit-root-ca

    ## Allowing use of ingress controllers
    ingress:
      enabled: true
      className: ""
      labels: {}
      annotations: {}
      hosts: 
        - host: drools-wb-cop.apps.apps.desa-rentas.gobiernocba.gov.ar
          paths:
            - path: /
              pathType: Prefix
    
    service:
      port: 8181
      targetPort: 8080
