project:
  repository_url: https://git.rentasweb.gob.ar/masterplan/backend/WSRest/wsrest-masterplan-generar-plan.git
  ecr_registry: 634937925704.dkr.ecr.us-west-2.amazonaws.com
  ecr_repository: wsrest-masterplan-generar-plan
