apiVersion: v2
name: ws-manager-resincronizador-del-30-cop
version: 0.0.1
Appversion: latest
description: >
    This Chart is to deploy ws-manager-resincronizador-del-30-cop proyect based on node Helm chart.
keywords:
  - node
dependencies:
- name: node
  version: 0.0.1
  # repository: "http://--/"
  repository: "file://../node"
