project:
  repository_url: https://git.rentasweb.gob.ar/Equipo-Contribuyentes-Especiales/contribuyentes-especiales/back/WS_Rest_Contribuyentes_Especiales.git
  ecr_registry: registry-sip.cba.gov.ar:5000
  ecr_repository: wsrestcontribuyentesespeciales